# Generated by Django 5.2.4 on 2025-07-26 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringpost',
            old_name='title',
            new_name='hiring_for',
        ),
        migrations.RenameField(
            model_name='hiringpost',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_title',
        ),
        migrations.AddField(
            model_name='hiringpost',
            name='personal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hiringpost',
            name='reason_for_hire',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pythonuser',
            name='custom_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pythonuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pythonuser',
            name='hired_users',
            field=models.ManyToManyField(blank=True, related_name='hired_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pythonuser',
            name='projects_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pythonuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='pythonuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
