# Generated by Django 5.2.4 on 2025-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('UI', 'UI Design'), ('WEB', 'Web Design'), ('APP', 'App Design'), ('GRAPHIC', 'Graphic Design')], default='UI', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(choices=[('ALL_RIGHTS', 'All Rights Reserved'), ('CC', 'Creative Commons'), ('MIT', 'MIT License')], default='ALL_RIGHTS', max_length=50),
        ),
    ]
