# Generated by Django 5.0 on 2025-07-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Select category'), ('UI', 'UI Design'), ('WEB', 'Web Design'), ('APP', 'App Design'), ('GRAPHIC', 'Graphic Design')], max_length=50, null=True),
        ),
    ]
